<?php
use Illuminate\Database\Seeder;
use App\Models\Producto;

class ProductosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
      $prod1 = Producto::create([
        'id'                => 1,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 60 ml',
        'sku'               => 'PRO-100',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 7.00,
        'utilid'            => '.3',
        'prec_clien'        => 10.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      /*
      $prod1->proveedores()->attach(1, [
        'prec_prove'  => '25.90',
        'utilid'      => '.3',
        'prec_clien'  => 37.00
      ]);
*/
      Producto::create([
        'id'                => 2,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 120 ml',
        'sku'               => 'PRO-101',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 25.90,
        'utilid'            => '.3',
        'prec_clien'        => 37.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 3,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 250 ml',
        'sku'               => 'PRO-102',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 11.20,
        'utilid'            => '.3',
        'prec_clien'        => 16.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 4,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 500 ml',
        'sku'               => 'PRO-103',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 18.20,
        'utilid'            => '.3',
        'prec_clien'        => 26.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 5,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 750 ml',
        'sku'               => 'PRO-104',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 23.80,
        'utilid'            => '.3',
        'prec_clien'        => 34.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 6,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 1 L',
        'sku'               => 'PRO-105',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 30.10,
        'utilid'            => '.3',
        'prec_clien'        => 43.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 7,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 5 L',
        'sku'               => 'PRO-106',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 25.90,
        'utilid'            => '.3',
        'prec_clien'        => 37.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 8,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 3.78 L',
        'sku'               => 'PRO-107',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 105.00,
        'utilid'            => '.3',
        'prec_clien'        => 150.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 9,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 20 L',
        'sku'               => 'PRO-108',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 518.00,
        'utilid'            => '.3',
        'prec_clien'        => 740.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 10,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 200 L',
        'sku'               => 'PRO-109',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 5109.30,
        'utilid'            => '.3',
        'prec_clien'        => 7299.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
      Producto::create([
        'id'                => 11,
        'produc'            => 'GEL ANTIBACTERIAL MAIZ 1000 L',
        'sku'               => 'PRO-110',
        'pro_de_cat'        => 'Si',
        'marc'              => 'Hand Defender',
        'tip'               => 'Producto',
        'cant_requerida'    => 0,
        'stock'             => '1150',
        'prove'             => 'GFJ PRODUCTS AND SERVICES SA DE CV',
        'prec_prove'        => 23655.80,
        'utilid'            => '.3',
        'prec_clien'        => 33794.00,
        'categ'             => 'Adicional',
        'pes'               => '0.000',
        'cod_barras'        => '-',
        'asignado_prod'  	  => 'desarrolloweb.ewmx@gmail.com',
        'created_at_prod'   => 'desarrolloweb.ewmx@gmail.com',
      ]);
    //  factory(App\Models\Producto::class, 1100)->create(); // Nota no puede haber mas armados que productos o fallaran los seeds
    // factory(App\Models\Producto::class, 9000)->create(); // Nota no puede haber mas armados que productos o fallaran los seeds
    }
}
